base_hostname: domain.test
tls:
  enabled: true
  acme_server: https://acme-v02.api.letsencrypt.org/directory
  use_hsts: true
smtp:
  enabled: true
  relay_host: relay.domain.test
  relay_port: 465
  # One of tls, starttls, or plain
  relay_protocol: tls
  relay_username: some_username
  relay_password: some_password
  # Unmonitored email address for services like the asset-manager
  from_address_noreply: noreply@domain.test
  # Monitored email address for services like the forum
  from_address_reply: reply@domain.test
  # Address that local daemons will default to sending to
  admin_address: admin@domain.test
  # Default domain used to replace localhost in the sender address
  default_domain: domain.test
homepage:
  enabled: true
  build_cron:
    # Email addresses that stakx build notifications should be sent to
    notify_addresses:
      - admin1@domain.test
      - admin2@domain.test
  privacy:
    # Website operator information
    operator:
      name: Joe Somebody
      email: joe@domain.test
  matomo:
    enabled: true
    cookie_domain: '*.domain.test'
    domains:
      - '*.domain.test'
    base_url: 'https://apps.domain.test/matomo/'
    site_id: 1006
forums:
  phpbb_version: 3.3.15
  archive_sha256: b4a1d0b579651dcdd55f02c0b742d23fb5d45f915de60628d5aadd34d32cf761
  # Upload archive from the same directory as the playbook instead of downloading from phpbb.com
  upload_local_archive: true
central:
  enabled: true
  enable_rest_api: true
asset_manager:
  enabled: true
  site:
    # Published address for DMCA takedown notices
    takedown_address: dmca@domain.test
  auth:
    # The forum group whose members are granted moderator rights on the asset manager
    admin_group: SOME.GROUP
  email:
    # Email address that should be notified about uploaded assets
    notify_addresses:
      - admin1@domain.test
      - admin2@domain.test
